# -----------------------------------------------------
# Environment Variables
# name: "Default"
# -----------------------------------------------------

# Mis cambios mejor visualizacion
# -----------------------------------------------------
# Environment Variables - HIBRIDO (Intel Main)
# -----------------------------------------------------

# 1. FORZAR WAYLAND (Para que se vea nítido en la Intel)
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# 2. CONFIGURACIÓN DE LIBRERÍAS GRÁFICAS
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland

# 3. COMPATIBILIDAD NVIDIA (Solo para prevenir errores)
# Esto ayuda si alguna vez la NVIDIA intenta dibujar algo, para que no explote.
env = LIBVA_DRIVER_NAME,iHD   # Usa el driver de Intel para video (mejor batería)
# Si tienes problemas de cursor invisible, descomenta la siguiente linea:
# env = WLR_NO_HARDWARE_CURSORS,1
