# ==============================================================================
# TEMA ACTIVO (THEME ENGINE PIVOT)
# ==============================================================================

# 1. BASE DEFAULT: Tu Súper Motor de Animaciones
source = ~/.config/hypr/themes/animations.conf

# 2. TEMA ELEGIDO: Colores, bordes, etc.
source = ~/.config/hypr/themes/cyberdream/theme.conf
