# ==============================================================================
# COMPORTAMIENTO DEL ENTORNO (Layouts & Misc)
# ==============================================================================

# --- 1. MOTOR DE VENTANAS (Dwindle) ---
dwindle {
    pseudotile = true       # Permite a las ventanas flotar falsamente dentro del tiling
    preserve_split = true   # Mantiene el orden espacial al cerrar/abrir ventanas
    smart_split = false
    smart_resizing = true
}

# --- 2. CONFIGURACIÓN MISCELÁNEA (Limpieza visual y Rendimiento) ---
misc {
    disable_hyprland_logo = true       # Adiós al logo de anime al arrancar
    disable_splash_rendering = true    # Adiós a los textos de advertencia rojos
    initial_workspace_tracking = 1
    
    vfr = true                         # Variable Frame Rate: Ahorra GPU cuando la pantalla está quieta
    vrr = 1                            # Variable Refresh Rate: Activa Freesync/G-Sync si tu monitor lo soporta
    
    # Animaciones extra (Estilo End-4)
    animate_manual_resizes = true      # Animación fluida al cambiar el tamaño con el mouse
    animate_mouse_windowdragging = true
}

# --- 3. COMPORTAMIENTO DE ESCRITORIOS ---
binds {
    workspace_back_and_forth = true    # UX Brutal: Si presionas el atajo del escritorio en el que ya estás, te devuelve al anterior.
    allow_workspace_cycles = true
    pass_mouse_when_bound = false
}
