# ==============================================================================
# CORE: MONITORES Y PANTALLAS
# ==============================================================================

# Pantalla principal (Tu Laptop) - Forzando su máxima resolución y Hz naturales
monitor = eDP-1, 1366x768@60, 0x0, 1

# Regla universal de fallback (Por si conectas un HDMI a un proyector o TV)
monitor = , preferred, auto, 1
