# ==============================================================================
# HYPRLAND MASTER (Zero-Noise Architecture)
# ==============================================================================

# 1. CORE & HARDWARE
source = ~/.config/hypr/core/env.conf
source = ~/.config/hypr/core/monitors.conf
source = ~/.config/hypr/core/inputs.conf
#source = ~/.config/hypr/core/gestures.lua
source = ~/.config/hypr/core/autostart.conf
source = ~/.config/hypr/core/keybinds.conf
source = ~/.config/hypr/core/window-rules.conf
source = ~/.config/hypr/core/behavior.conf

# 2. THEME ENGINE PIVOT
source = ~/.config/hypr/themes/active.conf
