# ==============================================================================
# HYPRIDLE CONFIGURATION (Power & Idle Management)
# ==============================================================================

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 1. Atenuar pantalla tras 8 min (480s)
listener {
    timeout = 480
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# 2. Activar Hyprlock tras 10 min (600s)
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# 3. Apagar monitor tras 11 min (660s)
listener {
    timeout = 660
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

# 4. Suspender laptop tras 30 min (1800s)
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
