# ==============================================================================
# MOTOR ESTÉTICO (Bordes, Gaps, Blur y Efecto Neón)
# ==============================================================================

general {
    border_size = 3
    gaps_in = 6
    gaps_out = 12

    # EFECTO FUEGO DORADO: Este gradiente girará eternamente gracias 
    # a la animación "borderangle" que configuramos antes.
    col.active_border = rgba(ffd700ff) rgba(ffec8bff) rgba(ffd700ff) 45deg
    col.inactive_border = rgba(333333aa)

    layout = dwindle
    resize_on_border = true
}

decoration {
    rounding = 12 
    
    # OPACIDAD BASE (La opacidad dinámica fuerte la manejan tus windowrules)
    active_opacity = 1.0
    inactive_opacity = 0.90
    
    # DIMMING: Oscurece ligeramente las ventanas que no tienen el foco (Estilo Jakoolit)
    dim_inactive = true
    dim_strength = 0.15

    # EL MEJOR BLUR DEL ECOSISTEMA
    blur {
        enabled = true
        size = 8
        passes = 3                     # 3 pases es el balance perfecto entre belleza y rendimiento
        ignore_opacity = true          # El blur se ve nítido incluso en ventanas muy transparentes
        new_optimizations = true
        xray = false
        vibrancy = 0.2                 # Saturation boost: Hace que los colores del wallpaper resalten a través del cristal
        popups = true                  # Aplica blur a los menús de click derecho y tooltips
    }

    # EFECTO NEÓN (SOMBRAS CON LUZ)
    shadow {
        enabled = true
        range = 30                     # Rango amplio para que parezca un brillo (Glow) y no una sombra dura
        render_power = 3
        color = rgba(ffd70088)         # Brillo dorado intenso cuando la ventana está activa
        color_inactive = rgba(00000000) # Se apaga completamente al perder el foco
    }
}
